remove version constraint and add target option
drone-plugins/drone-azure-storage pull request #11
Opened 2016-10-31 20:23 UTC by kaey

With current version of plugin, blobxfer
crashes with unknown BlobStorage traceback.
Removing version constraint and rebuilding
container helped.

Also PR adds target option, which allows specifying remote
path for blobs.

2016-10-31 20:35 UTC, tboerger requested changes

2016-10-31 20:35 UTC, tboerger commented on Dockerfile
> +  pip install blobxfer && \
I don't think that we want to drop the version constraints entirely, movies knows if the installed version really works properly with this code

2016-10-31 20:37 UTC, tboerger commented
Beside that, you got the wrong target, the 0.4 plugin only gets built from release/0.4 branch

2016-11-01 07:51 UTC, kaey commented
I didn't notice another pr here, which fixes version problem.
I've created another pr against 0.4 branch.

2016-11-01 07:51 UTC, closed without merging